# Generated by Django 4.0.2 on 2022-03-02 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('karbar', '0002_alter_karbar_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='meme_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='karbar',
            name='username',
            field=models.CharField(max_length=48),
        ),
    ]
