# Generated by Django 4.0.2 on 2022-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbar', '0003_alter_karbar_meme_id_alter_karbar_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='username',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
